services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - /home/valdir/Documents/projects/pessoal/rocketseat/python/mysql:/var/lib/mysql
    env_file:
      - .env